# Generated by Django 3.2.9 on 2021-12-30 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0003_rename_user_simulation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
