# Generated by Django 3.2.9 on 2021-12-30 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0004_auto_20211230_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='user',
        ),
        migrations.AddField(
            model_name='simulation',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
