# Generated by Django 3.2.9 on 2022-01-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0005_auto_20211230_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='user',
            new_name='user_shared_id',
        ),
        migrations.AddField(
            model_name='simulation',
            name='user_creator_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to='auth.user'),
            preserve_default=False,
        ),
    ]
