# Generated by Django 3.2.9 on 2022-01-02 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0006_auto_20220102_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='user_creator_id',
            new_name='user_creator',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='user_shared_id',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
