# Generated by Django 3.2.9 on 2022-01-02 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0007_auto_20220102_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='user_shared_id',
        ),
        migrations.AddField(
            model_name='simulation',
            name='user_shared',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
