# Generated by Django 3.2.9 on 2022-01-03 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0008_auto_20220102_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='user_shared',
        ),
        migrations.CreateModel(
            name='Partage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_creator_id', to=settings.AUTH_USER_MODEL)),
                ('user_shared', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_shared_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
