# Generated by Django 3.2.9 on 2022-01-03 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0009_auto_20220103_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partage_Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_shared_id', to='sim_manager.simulation')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_creator_id', to=settings.AUTH_USER_MODEL)),
                ('user_shared', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_shared_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Partage',
        ),
    ]
