# Generated by Django 3.2.9 on 2022-01-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sim_manager', '0010_auto_20220103_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partage_simulation',
            name='simulation_id',
        ),
        migrations.RemoveField(
            model_name='partage_simulation',
            name='user_creator',
        ),
        migrations.RemoveField(
            model_name='partage_simulation',
            name='user_shared',
        ),
        migrations.AddField(
            model_name='partage_simulation',
            name='destinataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partage_simulation',
            name='expediteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expediteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partage_simulation',
            name='simulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_shared_id', to='sim_manager.simulation'),
        ),
    ]
